version: '3.8'
services:
  grafana:
    image: grafana/grafana-oss
    container_name: grafana
    restart: unless-stopped
    user: '0'
    ports:
      - '3000:3000'
    volumes:
      - /Users/mateotorres2409/Developer/Code/github/serie-mundial/docker/volumes/grafana:/var/lib/grafana
    networks:
      - laboratory
  redis:
    image: redis/redis-stack:latest
    container_name: redis-stack
    restart: unless-stopped
    ports:
      - 6379:6379
      - 8001:8001
    volumes:
      - /Users/mateotorres2409/Developer/Code/github/serie-mundial/docker/volumes/redis/data:/data
      - /Users/mateotorres2409/Developer/Code/github/serie-mundial/docker/volumes/redis/redis-stack.conf:/redis-stack.conf
    networks:
      - laboratory
  mysql:
    image: mysql
    container_name: mysql
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: example
    volumes:
      - /Users/mateotorres2409/Developer/Code/github/serie-mundial/docker/volumes/mysql:/var/lib/mysql
    networks:
      - laboratory
  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080
    networks:
      - laboratory
networks:
  laboratory:
    name: laboratory

