name: pipeline-1
on:
    workflow_dispatch:
jobs:
    initial:   
        uses: mateotorres2409/serie-mundial-reusable@feature/initial
        with:
            name: ${{ vars.name }}
            version_other: feature/markdown
        secrets:
            gh_pat: ${{ secrets.gh_pat }}

