name: pipeline-3
on:    
    workflow_dispatch:
    push:
    deployment:    
    pull_request:
    release:
        types:
        - published
jobs:
    get_config:
        runs-on: ubuntu-latest
        steps:
        - name: workflow_dispatch
          if: github.event_name == 'workflow_dispatch'
          run: printf "workflow_dispatch ${{ github.event }}"
        - name: deployment
          if: github.event_name == 'deployment'
          run: printf "Deployment ${{ github.event }}"
        - name: push
          if: github.event_name == 'push'
          run: printf "push ${{ github.event }}"
        - name: pull_request
          if: github.event_name == 'pull_request'
          run: printf "pull_request ${{ github.event }}"
        - name: PR_Merged
          if: github.event_name == 'pull_request' && github.event.pull_request.merged == true
          run: printf "pull_request +  Merged ${{ github.event }}"
        - name: release
          if: github.event_name == 'release'
          run: printf "release ${{ github.event }}"