name: pipeline-1
on:    
    workflow_dispatch:
permissions:
    actions: read
jobs:
    initial:                   
        uses: mateotorres2409/serie-mundial-reusable/.github/workflows/hello_world.yml@feature/initial
        with:
            name: ${{ vars.name }}
            version_other: feature/markdown
            environment: integration
        secrets: inherit

            

