name: pipeline-1
on:
    workflow_dispatch:
jobs:
    initial:
        runs-on: ubuntu-latest
        steps:
            - name: checkout_current
              uses: actions/checkout@v3
            - name: print_hello
              run: |
                echo "Hello World!"