name: pipeline-1
on:    
    workflow_dispatch:
permissions:
    actions: read
jobs:
    initial:   
        uses: mateotorres2409/serie-mundial-reusable/.github/workflows/hello_world.yml@v0.0.1
        with:
            name: ${{ vars.name }}
            version_other: feature/markdown
        secrets:
            gh_pat: ${{ secrets.gh_pat }}

