name: pipeline-2
on:    
    workflow_dispatch:
    push:
        branches:
        - feature/**
jobs:
    get_config:
        runs-on: ubuntu-latest
        outputs:
            hostname: ${{ steps.getHostname.outputs.hostname }}
            ping: ${{ steps.getPing.outputs.ping }}
        steps:
        - name: checkout_current
          uses: actions/checkout@v4
          with:
            path: current
        - name: permission
          shell: bash
          run: chmod +x ./current/scripts/test_2.sh        
        - name: getHostname
          id: getHostname
          shell: bash
          run: ./current/scripts/test_2.sh     
        - name: getPing
          id: getPing
          shell: bash
          run: echo "ping=pong" >> "$GITHUB_OUTPUT"
    show_config:
        runs-on: ubuntu-latest
        needs: get_config
        steps:
        - env: 
            hostname: ${{ needs.get_config.outputs.hostname }}
            ping: ${{ needs.get_config.outputs.ping }}
          run: echo "$ping $hostname"
    
